apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master
  namespace: demo
spec:
  replicas: 1
  serviceName: es-master
  selector:
    matchLabels:
      application: elasticsearch
      role: master
  template:
    metadata:
      labels:
        application: elasticsearch
        role: master
    spec:
      serviceAccountName: operator
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox:1.30
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 50m
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
        image: "opensearchproject/opensearch:1.3.0"
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "OPENSEARCH_JAVA_OPTS"
          value: "-Xmx256m -Xms256m"
        - name: "node.master"
          value: "true"
        - name: "node.data"
          value: "false"
        - name: "cluster.name"
          value: "es-cluster"
        - name: "network.host"
          value: "0.0.0.0"
        - name: "bootstrap.memory_lock"
          value: "false"
        - name: "discovery.seed_hosts"
          value: "es-master"
        - name: "cluster.initial_master_nodes"
          value: "es-master-0"
        - name: "DISABLE_INSTALL_DEMO_CONFIG"
          value: "true"
        - name: "DISABLE_SECURITY_PLUGIN"
          value: "true"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 10
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: es-http
  namespace: demo
spec:
  selector:
    application: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: es-master
  namespace: demo
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    application: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
